from src.utils.constants import NodeType

class CodeGenerator:
    def __init__(self, graph, language="Python"):
        self.graph = graph
        self.language = language
        self.generated_code = []
        self.visited_on_path = set()

    def generate(self):
        start_nodes = [n for n, attr in self.graph.nodes(data=True) if attr["type"] == NodeType.START]
        if not start_nodes:
            return "// Error: No Start Node" if self.language == "C++" else "# Error: No Start Node"
        
        if self.language == "C++":
            self.generated_code = ["#include <iostream>", "#include <string>", "using namespace std;", "", "int main() {"]
            self.visit(start_nodes[0], 1)
            self.generated_code.append("    return 0;")
            self.generated_code.append("}")
        else:
            self.generated_code = ["# Generated by Flow2Code"]
            self.visit(start_nodes[0], 0)
            
        return "\n".join(self.generated_code)

    def visit(self, node, indent_level):
        indent = "    " * indent_level
        
        if node in self.visited_on_path:
            comment = "// Loop detected" if self.language == "C++" else "# Loop detected"
            self.generated_code.append(indent + comment)
            return
        
        self.visited_on_path.add(node)
        
        node_type = self.graph.nodes[node]["type"]
        text = self.graph.nodes[node]["text"]
        
        # Generate code for current node
        if self.language == "Python":
            self._generate_python(node_type, text, indent)
        else:
            self._generate_cpp(node_type, text, indent)

        # Handle Children/Edges
        children = list(self.graph.successors(node))
        
        if node_type == NodeType.DECISION:
            if not children:
                pass
            elif len(children) == 1:
                # Treated as simple connection
                self._generate_if_start(text, indent)
                self.visit(children[0], indent_level + 1)
                self._generate_block_end(indent)
            else:
                # Two branches
                self._generate_if_start(text, indent)
                self.visit(children[0], indent_level + 1)
                self._generate_block_end(indent) # End if block
                
                self._generate_else_start(indent)
                self.visit(children[1], indent_level + 1)
                self._generate_block_end(indent) # End else block
        else:
            # Linear flow
            for child in children:
                self.visit(child, indent_level)

        self.visited_on_path.remove(node)

    def _generate_python(self, node_type, text, indent):
        if node_type == NodeType.START:
            self.generated_code.append(indent + "# Start")
        elif node_type == NodeType.END:
            self.generated_code.append(indent + "exit()")
        elif node_type == NodeType.PROCESS:
            self.generated_code.append(indent + text)
        elif node_type == NodeType.INPUT:
             if "=" in text:
                 self.generated_code.append(indent + text)
             else:
                 self.generated_code.append(indent + f"{text} = input('Enter {text}: ')")
        elif node_type == NodeType.OUTPUT:
             self.generated_code.append(indent + f"print({text})")

    def _generate_cpp(self, node_type, text, indent):
        if node_type == NodeType.START:
            self.generated_code.append(indent + "// Start")
        elif node_type == NodeType.END:
            self.generated_code.append(indent + "return 0; // End")
        elif node_type == NodeType.PROCESS:
            stmt = text.strip()
            if not stmt.endswith(";"): stmt += ";"
            self.generated_code.append(indent + stmt)
        elif node_type == NodeType.INPUT:
             # Heuristic: "x" -> "int x; cin >> x;"
             var_name = text.split("=")[0].strip() if "=" in text else text
             # We assume int for simplicity if not declared
             self.generated_code.append(indent + f"int {var_name};") 
             self.generated_code.append(indent + f"cout << \"Enter {var_name}: \";")
             self.generated_code.append(indent + f"cin >> {var_name};")
        elif node_type == NodeType.OUTPUT:
             self.generated_code.append(indent + f"cout << {text} << endl;")

    def _generate_if_start(self, condition, indent):
        if self.language == "Python":
            self.generated_code.append(indent + f"if {condition}:")
        else:
            self.generated_code.append(indent + f"if ({condition}) {{")

    def _generate_else_start(self, indent):
        if self.language == "Python":
            self.generated_code.append(indent + "else:")
        else:
            self.generated_code.append(indent + "else {")

    def _generate_block_end(self, indent):
        if self.language == "C++":
            self.generated_code.append(indent + "}")
